export const CONTRACTOR_SECTIONS = [
  { id: "company_registration", label: "Company Registration" },
  { id: "coid_letter_of_good_standing", label: "COID / Letter of Good Standing" },
  { id: "organogram", label: "Organogram / Management Structure" },
  { id: "agreement_37_2", label: "37.2 Agreement" },
  { id: "appointment_16_2", label: "16.2 Appointment" },
  { id: "insurance", label: "Insurance" },
  { id: "health_safety_policy", label: "Health & Safety Policy" },
  { id: "ohs_plan", label: "OHS Plan" },
  { id: "notification_of_construction_work", label: "Notification of Construction Work" },
  { id: "baseline_risk_assessment", label: "Baseline Risk Assessment" },
  { id: "risk_assessments", label: "Risk Assessments" },
  { id: "fall_protection_plan", label: "Fall Protection Plan" },
  { id: "environmental_management_plan", label: "Environmental Management Plan" },
  { id: "method_statements", label: "Method Statements" },
  { id: "first_aider_appointment", label: "First Aider Appointment" },
  { id: "fire_fighter_appointment", label: "Fire Fighter Appointment" },
  { id: "training_certificates", label: "Training Certificates" },
  { id: "operator_licenses", label: "Operator Licenses" },
  { id: "competency_matrix", label: "Competency Matrix" },
  { id: "medical_fitness_certificates", label: "Medical Fitness Certificates" },
  { id: "inspections", label: "Inspections" },
  { id: "ppe_requirements", label: "PPE Requirements" },
  { id: "emergency_procedures", label: "Emergency Procedures" },
  { id: "environmental", label: "Environmental" },
  { id: "other", label: "Other" },
] as const;

export type ContractorSectionId = (typeof CONTRACTOR_SECTIONS)[number]["id"];
